### ISSUE TITLE
slack integration

### ISSUE THREAD

**Issue by jurgenvinju** [DagstuhlEAS/draft-report#1]
Hi @dgarijo  I would like to have my commits pushed to our slack channel but I believe I don't have the rights. Can you have a look?

**Comment by dgarijo** [comment]
Hi @jurgenvinju, 
everyone is an owner, so you should be able to do that...
Maybe you need to create a team for a particular repository

**Comment by danielskatz** [comment]
@dgarijo if you can help resolve this, it would be useful

**Comment by danielskatz** [comment]
Sorry @dgarijo, this is working.  commit messages go the slack "report" channel.

I'm going to close this issue
